server.port: 0

spring.application.name: payments-service

spring:
  datasource:
    url: "jdbc:h2:file:~/Users/b.galonja/code/axon-cqrs-course/payments-service/payments;AUTO_SERVER=true"
    username: root
    password: asd
    driver-class-name: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate.ddl-auto: update
  h2:
    console:
      enabled: true
      settings.web-allow-others: true
